config/routes.rb
# frozen_string_literal: true



Rails.application.routes.draw do

  resources :selection_controls
  resources :aesthetics

  resources :functions

  resources :system_controls

  resources :approvals

  resources :orders

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { sessions: 'sessions',

                                    registrations: 'registrations',

                                    passwords: 'passwords' }



  unauthenticated :user do

    root to: 'pages#index', id: 'index'

  end



  devise_scope :user do

    get 'login',  to: 'sessions#new'

    get 'logout', to: 'sessions#destroy'

    get 'register', to: 'devise/registrations#new'



    authenticate :user, ->(u) { u.admin? } do

      root to: 'products#index', as: :authenticated_admin

    end

  end



  resources :products do

    member do

      get :history

    end

    member do

      get :copy

    end
    
    member do

      get :clone

    end
    get 'model_selection', on: :new

    
  end

  get 'products_export', to: 'products#export', as: 'products_export'

  resources :features



  resource :searchable, only: [] do

    collection do

      get :features

    end

  end



  root to: 'pages#index'



  mount API::Base => '/'

  mount GrapeSwaggerRails::Engine => '/apidoc'

end


app/models/approval.rb
class Approval < ApplicationRecord
  include PgSearch
  pg_search_scope :search_approvals,
                  against: %i[approval_type sub_type approval_no],
                  using: { tsearch: { prefix: true, any_word: false } }
  has_many :product_approvals, dependent: :destroy
  has_many :products, through: :product_approvals
  accepts_nested_attributes_for :products, reject_if: :all_blank, allow_destroy: true
  mount_uploader :approval_doc, ApprovalDocUploader

  validates :approval_no, presence: true, uniqueness: { case_sensitive: false}

  def to_s
    @model_number
  end
end








app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_action :set_approval, only: %i[show edit update destroy]
  has_scope :search_approvals

  # GET /approvals
  def index
    @approvals = apply_scopes(Approval).page(params[:page]).per(10).order(updated_at: :desc)
  end

  # GET /approvals/1
  def show; end

  # GET /approvals/new
  def new
    @approval = Approval.new
  end

  # GET /approvals/1/edit
  def edit; end

  # POST /approvals
  def create
    @approval = Approval.new(approval_params)
    if @approval.save
      redirect_to @approval, notice: 'Approval was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /approvals/1
  def update
    if @approval.update(approval_params)
      redirect_to @approval, notice: 'Approval was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /approvals/1
  def destroy
    @approval.destroy
    redirect_to approvals_url, notice: 'Approval was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_approval
    @approval = Approval.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def approval_params
    # params.fetch(:approval, {})
    params.require(:approval).permit(:approval_type, :date, :approval_no, :sub_type, :description, :standard, :reference, :effective_date, :expiry_date, :status, :notes, :approval_doc, product_ids: [])
  end
end



app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/views/approvals/_form.html.slim
h3 Approval No. #{@approval.approval_no}
br

.row
  .col-xs-6
    /= f.input :approval_type, as: :string
    = f.input :approval_type, as: :select, collection: SelectionControl.where(name: 'approval type').pluck(:label), placeholder: "Choose a approval type"
  .col-xs-6
    = f.input :date, as: :string, placeholder: "DD/MM/YYYY"
.row
  .col-xs-6
    = f.input :approval_no, as: :string
  .col-xs-6
    = f.input :sub_type, as: :string
.row
  .col-xs-6
    = f.input :description, as: :string
  .col-xs-6
    = f.input :standard, as: :string
.row
  .col-xs-6
    = f.input :reference, as: :string
  .col-xs-6
    = f.input :effective_date, as: :string, placeholder: "DD/MM/YYYY"
.row
  .col-xs-6
    = f.input :expiry_date, as: :string, placeholder: "DD/MM/YYYY"
  .col-xs-6
    = f.input :status, as: :select, collection: ['Active', 'Inactive']
.row
  .col-xs-12
    = f.input :notes, as: :text

.row
  .col-xs-12
    h3 Associated Products
    = f.association :products, collection: Hash[Product.all.map { |product| [product.model_number, product.id] }], label: "Choose Model Number", input_html: { data: { toggle: 'multi-select2-fixed' }, multiple: true }
.row
  .col-xs-6
    h3 Approval Document
    = f.file_field :approval_doc

.nested-fields.file-item
  .file-container
  - if @approval.approval_doc.present?
    ul
      li = link_to "#{@approval.approval_doc.url}", @approval.approval_doc.url, target: '_blank'
  - else
    p = "No Documents Uploaded."
br
br
br
br
br
br
br
br
br
br
br
br

app/views/approvals/edit.html.slim
.container
  .row
    .col-xs-12
      h1 Edit Approval
  .row
    .col-xs-12
      = simple_form_for @approval do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          => f.submit 'Update', class: 'btn btn-primary'
          =< link_to "Cancel", :back, class: 'btn btn-default'

app/views/approvals/index.html.slim
/ h1 Listing approvals

/ table
/   thead
/     tr
/       th
/       th
/       th

/   tbody
/     - @approvals.each do |approval|
/       tr
/         td = link_to 'Show', approval
/         td = link_to 'Edit', edit_approval_path(approval)
/         td = link_to 'Destroy', approval, data: { confirm: 'Are you sure?' }, method: :delete

/ br

/ = link_to 'New Approval', new_approval_path


.container
  .row
    .col-xs-6
      h1 Approvals
    .col-xs-2.col-xs-offset-4
      = link_to "+ Add Approval", new_approval_path, class: 'btn btn-success btn-xs pull-right'
  br
  .row
    = form_tag(approvals_path, method: :get) do
      .col-xs-4
        = text_field_tag :search_approvals, nil, placeholder: "Search Approvals ...", class: "form-control"
      / .col-xs-4
      /   = select_tag :by_feature_type, options_for_select(Options::Products::Types.select_form), prompt: 'All Feature Types', class: "form-control"

      = submit_tag "Search / Reset", class: "btn btn-info btn-xs search-btn",style: ""
  br

  table.table
    tr
      th Approval No
      / th Type
      th Type
      th Sub Type
      th Expiry Date
      th Status
      th style='min-width:300px;'

    - for approval in @approvals
      tr
        td= approval.approval_no
        / td= I18n.t(feature.feature_type, scope: [:options, :product_types])
        td= approval.approval_type
        td= approval.sub_type
        td= approval.expiry_date
        td= approval.status
        td
          .btn-group.pull-right
            = link_to approval_path(approval), class: 'btn btn-default btn-xs' do
              i.fa.fa-eye
            = link_to edit_approval_path(approval), class: 'btn btn-default btn-xs' do
              i.fa.fa-pencil
            = link_to approval_path(approval), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
              i.fa.fa-trash-o
  = paginate @approvals

app/views/approvals/new.html.slim
.container
  .row
    .col-xs-12
      h1 New Approval
  .row
    .col-xs-12
      = simple_form_for @approval do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          => f.submit 'Create', class: 'btn btn-primary'
          =< link_to 'Cancel' , :back,  class: 'btn btn-default'

app/views/approvals/show.html.slim
.container
  h3 Approval No. #{@approval.approval_no}
  .btn-group.pull-right
    = link_to edit_approval_path(@approval), class: 'btn btn-default btn-xs' do
      i.fa.fa-pencil

  br
  br
  br

  table.table
    tr
      th Type
      td = @approval.approval_type

    tr
      th Date
      td = @approval.date

    tr
      th Approval No
      td = @approval.approval_no

    tr
      th Sub Type
      td = @approval.sub_type

    tr
      th Description
      td = @approval.description

    tr
      th Standard
      td = @approval.standard

    tr
      th Reference
      td = @approval.reference

    tr
      th Effective Date
      td = @approval.effective_date

    tr
      th Expiry Date
      td = @approval.expiry_date

    tr
      th Status
      td = @approval.approval_type

    tr
      th Notes
      td = @approval.notes
  
  h3 Products
  .row
    .col-xs-12
      - if @approval.products.any?
        table class="table table-sm"
          tr 
            th Model NO.
            th Description
          - for prd in @approval.products
            tr
              td = link_to "#{prd.model_number}", product_path(prd)
              td = prd.description
      - else
        p = "No Products Connected."

  h3 Documents
  .row
    .col-xs-12
      - if @approval.approval_doc.present?
        ul
          li = link_to "#{@approval.approval_doc.url}", @approval.approval_doc.url, target: '_blank'
      - else
        p = "No Documents Uploaded."
  .btn-group.pull-left
    = link_to approvals_path, class: 'btn btn-default btn-xs' do
      i.fa.fa-arrow-left