config/routes.rb
# frozen_string_literal: true



Rails.application.routes.draw do

  resources :selection_controls
  resources :aesthetics

  resources :functions

  resources :system_controls

  resources :approvals

  resources :orders

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { sessions: 'sessions',

                                    registrations: 'registrations',

                                    passwords: 'passwords' }



  unauthenticated :user do

    root to: 'pages#index', id: 'index'

  end



  devise_scope :user do

    get 'login',  to: 'sessions#new'

    get 'logout', to: 'sessions#destroy'

    get 'register', to: 'devise/registrations#new'



    authenticate :user, ->(u) { u.admin? } do

      root to: 'products#index', as: :authenticated_admin

    end

  end



  resources :products do

    member do

      get :history

    end

    member do

      get :copy

    end
    
    member do

      get :clone

    end
    get 'model_selection', on: :new

    
  end

  get 'products_export', to: 'products#export', as: 'products_export'

  resources :features



  resource :searchable, only: [] do

    collection do

      get :features

    end

  end



  root to: 'pages#index'



  mount API::Base => '/'

  mount GrapeSwaggerRails::Engine => '/apidoc'

end


app/models/aesthetic.rb
class Aesthetic < ApplicationRecord
  include PgSearch
  pg_search_scope :search_aesthetics,
                  against: %i[aesthetic_code aesthetic_description],
                  using: { tsearch: { prefix: true, any_word: false } }
  validates :aesthetic_code, presence: true, uniqueness: { case_sensitive: false}
  validates :aesthetic_description, presence: true
end


app/models/options/aesthetics.rb
module Options
  class Aesthetics < Base
    def initialize(option)
      @option = option
    end

    @options = %w[
      portofino
      classic
      linear
      victoria
    ]

    def to_s
      I18n.t @option, scope: %i[options aesthetics]
    end
  end
end

app/controllers/aesthetics_controller.rb
class AestheticsController < ApplicationController
  before_action :set_aesthetic, only: %i[show edit update destroy]

  has_scope :search_aesthetics

  # GET /aesthetics
  def index
    @aesthetics = apply_scopes(Aesthetic).page(params[:page]).per(10).order(updated_at: :desc)
  end

  # GET /aesthetics/1
  def show; end

  # GET /aesthetics/new
  def new
    @aesthetic = Aesthetic.new
  end

  # GET /aesthetics/1/edit
  def edit; end

  # POST /aesthetics
  def create
    @aesthetic = Aesthetic.new(aesthetic_params)

    if @aesthetic.save
      redirect_to aesthetics_url, notice: 'Aesthetic was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /aesthetics/1
  def update
    if @aesthetic.update(aesthetic_params)
      redirect_to aesthetics_url, notice: 'Aesthetic was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /aesthetics/1
  def destroy
    @aesthetic.destroy
    redirect_to aesthetics_url, notice: 'Aesthetic was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_aesthetic
    @aesthetic = Aesthetic.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def aesthetic_params
    params.require(:aesthetic).permit(:control_type, :aesthetic_description, :aesthetic_code)
  end
end

app/helpers/aesthetics_helper.rb
module AestheticsHelper
end

app/views/aesthetics/_form.html.slim
/ = simple_form_for(@aesthetic) do |f|
/   = f.error_notification
/
/   .form-inputs
/     = f.input :control_type
/     = f.input :aesthetic_description
/     = f.input :aesthetic_code
/
/   .form-actions
/     = f.button :submit


h3 #{@aesthetic.control_type}
br

/ .row
/   .col-xs-6
/     = f.input :control_type, as: :string
.row
  .col-xs-6
    = f.input :aesthetic_code, as: :string
.row
  .col-xs-6
    = f.input :aesthetic_description, as: :string

app/views/aesthetics/edit.html.slim
/ h1 Editing aesthetic
/
/ == render 'form'
/
/ = link_to 'Show', @aesthetic
/ '|
/ = link_to 'Back', aesthetics_path
/


.container
  .row
    .col-xs-12
      h1 Edit Aesthetic

  .row
    .col-xs-12
      = simple_form_for @aesthetic do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          => f.submit 'Update', class: 'btn btn-primary'
          =< link_to "Cancel", :back, class: 'btn btn-default'

app/views/aesthetics/index.html.slim
/ h1 Listing aesthetics
/
/ table
/   thead
/     tr
/       th Control type
/       th Aesthetic description
/       th Aesthetic code
/       th
/       th
/       th
/
/   tbody
/     - @aesthetics.each do |aesthetic|
/       tr
/         td = aesthetic.control_type
/         td = aesthetic.aesthetic_description
/         td = aesthetic.aesthetic_code
/         td = link_to 'Show', aesthetic
/         td = link_to 'Edit', edit_aesthetic_path(aesthetic)
/         td = link_to 'Destroy', aesthetic, data: { confirm: 'Are you sure?' }, method: :delete
/
/ br
/
/ = link_to 'New Aesthetic', new_aesthetic_path


.container
  .row
    .col-xs-6
      h1 Aesthetics
    .col-xs-2.col-xs-offset-4
      = link_to "+ Add Aesthetic", new_aesthetic_path, class: 'btn btn-success btn-xs pull-right'
  br
  .row
    = form_tag(aesthetics_path, method: :get) do
      .col-xs-4
        = text_field_tag :search_aesthetics, nil, placeholder: "Search Aesthetics ...", class: "form-control"
      / .col-xs-4
      /   = select_tag :by_feature_type, options_for_select(Options::Products::Types.select_form), prompt: 'All Feature Types', class: "form-control"

      = submit_tag "Search / Reset", class: "btn btn-info btn-xs search-btn",style: ""
  br
  table.table
    tr
      /th Control Type
      / th Type
      th Aesthetic Code
      th Aesthetic Descrption
      / th Created At
      th style='min-width:300px;'

    - for aesthetic in @aesthetics
      tr
        /td= aesthetic.control_type
        / td= I18n.t(feature.feature_type, scope: [:options, :product_types])

        td= aesthetic.aesthetic_code
        td= aesthetic.aesthetic_description
        / td= aesthetic.created_at
        td
          .btn-group.pull-right
            = link_to aesthetic_path(aesthetic), class: 'btn btn-default btn-xs' do
              i.fa.fa-eye
            = link_to edit_aesthetic_path(aesthetic), class: 'btn btn-default btn-xs' do
              i.fa.fa-pencil
            = link_to aesthetic_path(aesthetic), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
              i.fa.fa-trash-o
  = paginate @aesthetics

app/views/aesthetics/new.html.slim
/ h1 New aesthetic
/
/ == render 'form'
/
/ = link_to 'Back', aesthetics_path

.container
  .row
    .col-xs-12
      h1 New Aesthetic

  .row
    .col-xs-12
      = simple_form_for @aesthetic do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          => f.submit 'Create', class: 'btn btn-primary'
          =< link_to "Cancel", :back, class: 'btn btn-default'

app/views/aesthetics/show.html.slim
/ p#notice = notice
/
/ p
/   strong Control type:
/   = @aesthetic.control_type
/ p
/   strong Aesthetic description:
/   = @aesthetic.aesthetic_description
/ p
/   strong Aesthetic code:
/   = @aesthetic.aesthetic_code
/
/ = link_to 'Edit', edit_aesthetic_path(@aesthetic)
/ '|
/ = link_to 'Back', aesthetics_path



.container
  h3 Aesthetic
  .btn-group.pull-right
    = link_to edit_aesthetic_path(@aesthetic), class: 'btn btn-default btn-xs' do
      i.fa.fa-pencil

  br
  br
  br

.container
  table.table
    / tr
    /   th Control Type
    /   td = @aesthetic.control_type
    / tr
    /   th Category
    /   td = @feature.feature_type
    tr
      th Aesthetic Code
      td = @aesthetic.aesthetic_code

    tr
      th Aesthetic Description
      td = @aesthetic.aesthetic_description
  .btn-group.pull-left
    = link_to aesthetics_path(@aesthetic), class: 'btn btn-default btn-xs' do
      i.fa.fa-arrow-left