config/routes.rb
# frozen_string_literal: true



Rails.application.routes.draw do

  resources :selection_controls
  resources :aesthetics

  resources :functions

  resources :system_controls

  resources :approvals

  resources :orders

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { sessions: 'sessions',

                                    registrations: 'registrations',

                                    passwords: 'passwords' }



  unauthenticated :user do

    root to: 'pages#index', id: 'index'

  end



  devise_scope :user do

    get 'login',  to: 'sessions#new'

    get 'logout', to: 'sessions#destroy'

    get 'register', to: 'devise/registrations#new'



    authenticate :user, ->(u) { u.admin? } do

      root to: 'products#index', as: :authenticated_admin

    end

  end



  resources :products do

    member do

      get :history

    end

    member do

      get :copy

    end
    
    member do

      get :clone

    end
    get 'model_selection', on: :new

    
  end

  get 'products_export', to: 'products#export', as: 'products_export'

  resources :features



  resource :searchable, only: [] do

    collection do

      get :features

    end

  end



  root to: 'pages#index'



  mount API::Base => '/'

  mount GrapeSwaggerRails::Engine => '/apidoc'

end


app/models/function.rb
class Function < ApplicationRecord
  include PgSearch
  pg_search_scope :search_functions, against: %i[product_type description],using: { tsearch: { prefix: true, any_word: false } }
  mount_uploader :url, FunctionIconUploader
  validates :product_type, presence: true
  validates :function_code, presence: true
end






app/models/options/functions.rb
module Options
  class Functions < Base

    class Types < Roles

      def initialize(option)
        @option = option
      end

      @options = %w(
                  pyrolytic_cleaning
                  eco_pyrolytic
                  pyrolytic
                  defrost_proofing_dehydrate_warming
                  static_grill
                  convection
                  fan_forced
                  fan_grill
                  fan_assisted
                  bakers_function
                  supercook
                  eco
                  microwave
                  microwave_grill
                  microwave_fan_forced
                  microwave_static_fan
                  vapour_clean
                  defrost_by_time
                  defrost_by_weight
                  proving
                  sabbath_mode
                  keep_warm
                  reheat
                  steam
                  base_heat
                  bakers_microwave
                  fan_forced_grill
                  half_grill
                  super_fan_force
                  fan_forced_steam
                  fan_assisted_gas
                  rotisserie
                  grill_element
                  rotisserie_full
                  half_static_grill
                  pizza
                  quicktime
                  flexizone
                  delay
                  flexitab
                  enersave
                  aquatest
                  orbital_system
                  eco_fan_forced
                  meat
                  vegetables
                  pasta
                  cake
                  potato
                  fish
                  beverage
                  popcorn
                  chicken
                  frozen_pizza
                  frozen_vegetables
                  fresh_vegetables
                  dish_warmer
                  cake_bread
                  fresh_pizaa
                  fresh_gratin
                  frozen_gratin
                  combination
                  defrost_proofing_dehydrate_warming

                  fully_automatic_coffee_preparation
                  automatic_cappuccino_maker
                  ground_coffee_option
                  hot_water_function
                  rinsing_function
                  steam_function
                  automatic_milk_frother

                  prewash
                  quick_rinse
                  extra_rinse
                  memory
                  dryness_adjustment_level
                )

      def to_s
        I18n.t @option, scope: [:options, :function_list]
      end

    end
  end
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  before_action :set_function, only: %i[show edit update destroy]
  has_scope :search_functions

  # GET /functions
  def index
    @functions = apply_scopes(Function).page(params[:page]).per(10).order(updated_at: :desc)
  end

  # GET /functions/1
  def show; end

  # GET /functions/new
  def new
    @function = Function.new
  end

  # GET /functions/1/edit
  def edit; end

  # POST /functions
  def create
    @function = Function.new(function_params)
    if @function.save
      redirect_to functions_url, notice: 'Function was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /functions/1
  def update
    if @function.update(function_params)
      redirect_to functions_url, notice: 'Function was successfully updated.'
      # flash[:notice] = "This is notice"
      # redirect_to functions_url
    else
      render :edit
    end
  end

  # DELETE /functions/1
  def destroy
    @function.destroy
    redirect_to functions_url, notice: 'Function was successfully destroyed.'
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_function
    @function = Function.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def function_params
    params.require(:function).permit(:control_type, :product_type, :function_code, :description, :url)
  end
end



app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/functions/_form.html.slim
/ = simple_form_for(@function) do |f|
/   = f.error_notification
/
/   .form-inputs
/     = f.input :control_type
/     = f.input :product_type
/     = f.input :function_code
/     = f.input :description
/
/   .form-actions
/     = f.button :submit



/ .row
/   .col-xs-6
/     = f.input :control_type, as: :string
.row
  .col-xs-6
    = f.input :product_type, as: :string
.row
  .col-xs-6
    = f.input :function_code, as: :string
.row
  .col-xs-6
    = f.input :description, as: :string
.row
  .col-xs-6
    = f.input :url, as: :string
.row
  .col-xs-6.icon_size
    = image_tag(@function.url)
.row
  .col-xs-6
    = f.file_field :url

app/views/functions/edit.html.slim
/ h1 Editing function
/
/ == render 'form'
/
/ = link_to 'Show', @function
/ '|
/ = link_to 'Back', functions_path

.container
  .row
    .col-xs-12
      h1 Edit Function

  .row
    .col-xs-12
      = simple_form_for @function do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          => f.submit 'Update', class: 'btn btn-primary'
          =< link_to "Cancel", :back, class: 'btn btn-default'

app/views/functions/index.html.slim
/ h1 Listing functions
/
/ table
/   thead
/     tr
/       th Control type
/       th Product type
/       th Function code
/       th Descritpion
/       th
/       th
/       th
/
/   tbody
/     - @functions.each do |function|
/       tr
/         td = function.control_type
/         td = function.product_type
/         td = function.function_code
/         td = function.description
/         td = link_to 'Show', function
/         td = link_to 'Edit', edit_function_path(function)
/         td = link_to 'Destroy', function, data: { confirm: 'Are you sure?' }, method: :delete
/
/ br
/
/ = link_to 'New Function', new_function_path

/ h1 System Controls

/ table
/   thead
/     tr
/       th
/       th
/       th

/   tbody
/     - @system_controls.each do |system_control|
/       tr
/         td = link_to 'Show', system_control
/         td = link_to 'Edit', edit_system_control_path(system_control)
/         td = link_to 'Destroy', system_control, data: { confirm: 'Are you sure?' }, method: :delete

/ br

/ = link_to 'New System control', new_system_control_path


.container
  .row
    .col-xs-6
      h1 Functions
    .col-xs-2.col-xs-offset-4
      = link_to "+ Add Function", new_function_path, class: 'btn btn-success btn-xs pull-right'
  br
  .row
    = form_tag(functions_path, method: :get) do
      .col-xs-4
        = text_field_tag :search_functions, nil, placeholder: "Search Functions ...", class: "form-control"
      / .col-xs-4
      /   = select_tag :by_feature_type, options_for_select(Options::Products::Types.select_form), prompt: 'All Feature Types', class: "form-control"

      = submit_tag "Search / Reset", class: "btn btn-info btn-xs search-btn",style: ""
  br
  table.table
    tr
      / th Control Type
      / th Type
      th Product Type
      th Function Code
      th Description
      th Icon
      / th Created At
      th style='min-width:300px;'

    - for function in @functions
      tr
        / td= function.control_type
        / td= I18n.t(feature.feature_type, scope: [:options, :product_types])

        td= function.product_type
        td= function.function_code
        td= function.description
        td.icon_size= image_tag(function.url)
        / td= function.created_at
        td
          .btn-group.pull-right
            = link_to function_path(function), class: 'btn btn-default btn-xs' do
              i.fa.fa-eye
            = link_to edit_function_path(function), class: 'btn btn-default btn-xs' do
              i.fa.fa-pencil
            = link_to function_path(function), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
              i.fa.fa-trash-o
  = paginate @functions

app/views/functions/new.html.slim
/ h1 New function
/
/ == render 'form'
/
/ = link_to 'Back', functions_path


.container
  .row
    .col-xs-12
      h1 New Function

  .row
    .col-xs-12
      = simple_form_for @function do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          => f.submit 'Create', class: 'btn btn-primary'
          =< link_to 'Cancel' , :back,  class: 'btn btn-default'

app/views/functions/show.html.slim
/ p#notice = notice
/
/ p
/   strong Control type:
/   = @function.control_type
/ p
/   strong Product type:
/   = @function.product_type
/ p
/   strong Function code:
/   = @function.function_code
/ p
/   strong Descritpion:
/   = @function.description
/
/ = link_to 'Edit', edit_function_path(@function)
/ '|
/ = link_to 'Back', functions_path


.container
  h3 Function
  .btn-group.pull-right
    = link_to edit_function_path(@function), class: 'btn btn-default btn-xs' do
      i.fa.fa-pencil

  br
  br
  br

.container
  table.table
    / tr
    /   th Control Type
    /   td = @function.control_type
    / tr
    /   th Category
    /   td = @feature.feature_type
    tr
      th Product Type
      td = @function.product_type

    tr
      th Function Code
      td = @function.function_code

    tr
      th Description
      td = @function.description
    tr
      th Icon
      td.icon_size = image_tag(@function.url)

  .btn-group.pull-left
    = link_to functions_path, class: 'btn btn-default btn-xs' do
      i.fa.fa-arrow-left