config/routes.rb
# frozen_string_literal: true



Rails.application.routes.draw do

  resources :selection_controls
  resources :aesthetics

  resources :functions

  resources :system_controls

  resources :approvals

  resources :orders

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, controllers: { sessions: 'sessions',

                                    registrations: 'registrations',

                                    passwords: 'passwords' }



  unauthenticated :user do

    root to: 'pages#index', id: 'index'

  end



  devise_scope :user do

    get 'login',  to: 'sessions#new'

    get 'logout', to: 'sessions#destroy'

    get 'register', to: 'devise/registrations#new'



    authenticate :user, ->(u) { u.admin? } do

      root to: 'products#index', as: :authenticated_admin

    end

  end



  resources :products do

    member do

      get :history

    end

    member do

      get :copy

    end
    
    member do

      get :clone

    end
    get 'model_selection', on: :new

    
  end

  get 'products_export', to: 'products#export', as: 'products_export'

  resources :features



  resource :searchable, only: [] do

    collection do

      get :features

    end

  end



  root to: 'pages#index'



  mount API::Base => '/'

  mount GrapeSwaggerRails::Engine => '/apidoc'

end


app/models/options/products.rb
module Options
  class Products < Base

    class Types < Roles

      def initialize(option)
        @option = option
      end

      @options = %w(
                  CeramicElectricCooktop
                  ClassicCoffeeMachine
                  ClassicCompact
                  ClassicDoubleOven
                  ClassicOven70
                  ClassicOven76
                  ClassicOven90
                  ClassicOvenMidrange
                  Dishwasher
                  DominoCooktop
                  FabRefrigeration
                  FreestandingCooker70
                  FreestandingCooker90
                  FreestandingCooker120
                  FreestandingCooker150
                  FrenchDoorRefrigeration
                  GasCooktop
                  WashingMachine
                  Dryer
                  InductionCooktop
                  LinearCompact
                  LinearOven
                  LinearRangehood
                  Microwave
                  UndermountRangehood
                  VictoriaCompact
                  VictoriaDoubleOven
                  VictoriaFreestandingCooker90
                  VictoriaFreestandingCooker93
                  VictoriaFreestandingCooker110
                  PortofinoFreestandingCooker90
                  VictoriaOven
                  VictoriaRangehood
                  PortofinoRangehood
                  WallmountRangehood
                  WarmingDrawer
                  GasInductionDominoCooktop

                  # added
                  Oven
                  WasherDryer
                  FreestandingCooker
                  FreestandingCooker2
                  CoffeeMachine
                )

      def to_s
        I18n.t @option, scope: [:options, :product_types]
      end

    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch
  include Trailable
  extend FriendlyId

  friendly_id :model_number, use: :slugged
  mount_uploader :cover_image, ImageUploader
  has_paper_trail
  has_many :product_features, dependent: :destroy
  has_many :features, through: :product_features
  has_many :product_approvals, dependent: :destroy
  has_many :approvals, through: :product_approvals
  has_many :product_attachments, dependent: :destroy
  has_many :image_attachments, through: :product_attachments, source: :attachment, class_name: 'ImageAttachment', dependent: :destroy
  has_many :schematic_attachments, through: :product_attachments, source: :attachment, class_name: 'SchematicAttachment', dependent: :destroy
  has_many :file_attachments, through: :product_attachments, source: :attachment, class_name: 'FileAttachment', dependent: :destroy

  accepts_nested_attributes_for :features, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :image_attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :schematic_attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :file_attachments, reject_if: :all_blank, allow_destroy: true

  accepts_nested_attributes_for :approvals, reject_if: :all_blank, allow_destroy: true
  pg_search_scope :search_products,
                  against: %i[model_number type description],
                  using: { tsearch: { prefix: true } }
  scope :by_type, -> type { where(type: type) }
  scope :by_aesthetic, -> aesthetic { where(aesthetic: aesthetic) }
  scope :by_status, -> status { where(status: status)}

  validates :model_number, presence: true, uniqueness: { case_sensitive: false }
  validates :type, presence: true, exclusion: { in: %w(Product), message: ": Please select product type." }
  before_validation :assign_type

  def history
    own_papertrail_history = papertrail_history || []
  end

  def self.to_csv(ptype)

    puts ptype
    cl = Product.find_by(type: ptype)
    #puts t
    #puts p_type
    # cl = Product.find_by(type: p_type)
    # puts cl.class
    #attributes = %w{id  model_number type description aesthetic dimensions finish supplied_accessories optional_accessories safety power warranty status data notes ean price }
    #attributes = Product.column_names() + cl.data.keys
    attributes = Product.column_names() + (cl.data==nil ? []: cl.data.keys)
    attributes.delete('data')
    attributes << 'features'
  
    #attributes << cl.data.keys
    CSV.generate(headers: true) do |csv|
      csv << attributes
      Product.where(type: ptype).each do |product|
        #csv<< attributes.map{ |attr| product.send(attr).kind_of?(Array) ? product.send(attr).join("\n") : product.send(attr)}
        csv<< attributes.map{ |attr| attr == 'features' ? product.send(attr).pluck('name').join("\n") : (product.send(attr).kind_of?(Array) ? product.send(attr).join("\n") : product.send(attr))}
      end
    end
  end

  def self.tester(num)
    puts num
  end

  private
  def assign_type
    self.type = self.class.to_s if type.blank?
  end

  def self.unique_type
    self.distinct.order(:type).pluck(:type) 
  end

  def self.unique_aesthetic
    self.distinct.pluck(:aesthetic).reject { |x| x.to_s.empty? }
  end

  # def self.get_value_by_attr
  #   self.data.find()
  # end



end




app/models/products/accessories.rb
class Accessories < Product

  jsonb_accessor :data,

    # no 
    function_list: [:string, array: true, default: []]

end

app/models/products/bbq.rb
class  BBQ< Product

    jsonb_accessor :data,
      gas_output: :string,
      size: :string,
      thermostat: :string,
      weight: :string  
end
  

app/models/products/ceramic_electric_cooktop.rb
class CeramicElectricCooktop < Product

  jsonb_accessor :data,
    capacity: [:string, array: true, default: []],
    installation: :string,
    controls: :string,
    size: :string,
    timers: [:string, array: true, default: []],
    power_levels: :string,
    cutout: [:string, array: true, default: []],
    
    # no 
    gas_connection: [:string, array: true],
    function_list: [:string, array: true, default: []]

end

app/models/products/classic_compact.rb
class ClassicCompact < Product

  jsonb_accessor :data,
    total_functions: [:string, array: true, default: []],
    device_display: :string,
    capacity: [:string, array: true, default: []],
    cooking_levels: :string,
    thermostat: :string,
    water_tank_capacity: :string,
    microwave_power: :string,
    installation: :string,
    programmability: [:string, array: true, default: []],
    cleaning: :string,
    lighting: :string,
    function_list: [:string, array: true, default: []],


    # no
    auto_menus: :string

end

app/models/products/classic_double_oven.rb
class ClassicDoubleOven < Product

  jsonb_accessor :data,
    device_display: :string,
    installation: :string,

    # Added attribute capacity
    capacity: [:string, array: true, default: []],
    cleaning: :string,
    cooking_levels: :string,
    lighting: :string,
    thermostat: :string,
    programmability: [:string, array: true, default: []],
    function_list: [:string, array: true, default: []],
    total_functions: [:string, array: true, default: []],


     # no
    main_oven: :string,
    auto_menus: :string,
    capacity_main_oven: [:string, array: true, default: []],
    total_functions_main_oven: [:string, array: true, default: []],
    cooking_levels_main_oven: :string,
    thermostat_main_oven: :string,
    programmability_main_oven: [:string, array: true, default: []],
    cleaning_main_oven: :string,
    lighting_main_oven: :string,
    supplied_accessories_main_oven: [:string, array: true, default: []],

    capacity_aux_oven: [:string, array: true, default: []],
    total_functions_aux_oven: [:string, array: true, default: []],
    cooking_levels_aux_oven: :string,
    thermostat_aux_oven: :string,
    supplied_accessories_aux_oven: [:string, array: true, default: []],
    programmability_aux_oven: [:string, array: true, default: []],
    cleaning_aux_oven: :string,
    lighting_aux_oven: :string,

    function_list_main_oven: [:string, array: true, default: []],
    function_list_aux_oven: [:string, array: true, default: []]
end

app/models/products/coffee_machine.rb
class CoffeeMachine < Product

    jsonb_accessor :data,
        cleaning: :string,
        coffee_bean_capacity: :string,
        device_display: :string,
        functions: [:string, array: true, default: []],
        installation: :string,
        lighting: :string,
        programmability: [:string, array: true, default: []],
        pump_pressure: :string,
        size: :string,
        thermostat: :string,
        water_tank_capacity: :string,
  
        # no
        function_list: [:string, array: true, default: []]

end

app/models/products/dishwasher.rb
class Dishwasher < Product

  jsonb_accessor :data,
    baskets: :string,
    capacity: [:string, array: true, default: []],
    device_display: :string,
    drying: :string,
    end_of_cycle_indicator: :string,
    energy_rating: :string,
    energy_usage: :string,
    feature_list: [:string, array: true, default: []],
    filtration: :string,
    function_list: [:string, array: true, default: []],
    noise: :string,
    programs_list: [:string, array: true, default: []],
    quick_programs_list: [:string, array: true, default: []],
    size: :string,
    temperatures: :string,
    timer: :string,
    total_programs: :string,
    style: :string,
    wash_system: [:string, array: true, default: []],
    water_connection: :string,
    water_softener: :string,
    water_usage: :string,
    water_rating: :string,


    # no
    programmability: [:string, array: true, default: []]

end

app/models/products/dolce_compact.rb
class DolceCompact < Product

  jsonb_accessor :data,
    auto_menus: :string,
    capacity: [:string, array: true, default: []],
    cavity: :string,
    cleaning: :string,
    cooking_levels: :string,
    device_display: :string,
    installation: :string,
    lighting: :string,
    microwave_power: :string,
    programmability: :string,
    thermostat: :string,
    total_functions: [:string, array: true, default: []],
    water_tank_capacity: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/dolce_wine.rb
class DolceWine < Product

  jsonb_accessor :data,
    air_filter: :string,
    capacity: [:string, array: true, default: []],
    cooling: :string,
    device_display: :string,
    door: :string,
    installation: :string,
    lighting: :string,
    shelves: [:string, array: true, default: []],
    thermostat: :string,

    function_list: [:string, array: true, default: []]

end

app/models/products/domino.rb
class Domino < Product

  jsonb_accessor :data,
    capacity: [:string, array: true, default: []],
    gas_connection: [:string, array: true],
    installation: :string,
    burners: :string,
    temperature_control: :string,
    cutout: [:string, array: true, default: []],
    
    # no 
    function_list: [:string, array: true, default: []]

end

app/models/products/fab_refrigeration.rb
class FabRefrigeration < Product

  jsonb_accessor :data,
    accessories: [:string, array: true, default: []],
    defrost: :string,
    energy_consumption: :string,
    gross_capacity: [:string, array: true, default: []],
    lighting: :string,
    nb_of_drawers: [:string, array: true, default: []],
    nb_drawers: [:string, array: true, default: []],
    nb_shelves: [:string, array: true, default: []],
    noise: :string,
    star_rating: :string,

    # no 
    shelves_main_compartment: [:string, array: true, default: []],
    drawers_main_compartment: [:string, array: true, default: []],
    lighting_main_compartment: [:string, array: true, default: []],

    shelves_inner_door: [:string, array: true, default: []],
    accessories_inner_door: [:string, array: true, default: []],

    shelves_freezer: [:string, array: true, default: []],
    drawers_freezer: [:string, array: true, default: []],
    accessories_freezer: [:string, array: true, default: []],

    performance: :string,
    function_list: [:string, array: true, default: []]
end

app/models/products/freestanding_cooker.rb
class FreestandingCooker < Product

  jsonb_accessor :data,
    auto_menus: :string,
    capacity: [:string, array: true, default: []],
    cleaning: :string,
    description_2: :string,
    cooking_levels: :string,
    device_display: :string,
    door_glass: :string,

    function_list: [:string, array: true, default: []],
    gas_input: :string,
    installation: :string,
    lighting: :string,
    main_oven: :string,
    programmability: [:string, array: true, default: []],
    thermostat: :string,
    total_functions: [:string, array: true, default: []],

    # no
    capacity_gas_hob: [:string, array: true, default: []],
    safety_gas_hob: [:string, array: true, default: []],
    supplied_accessories_gas_hob: [:string, array: true, default: []],
    capacity_electric_hob: [:string, array: true, default: []],
    safety_electric_hob: [:string, array: true, default: []],
    supplied_accessories_electric_hob: [:string, array: true, default: []],
    supplied_accessories_main_oven: [:string, array: true, default: []]
end

app/models/products/freestanding_cooker2.rb
class FreestandingCooker2 < Product

  jsonb_accessor :data,
    barbecue: :string,
    capacity: [:string, array: true, default: []],
    cleaning: :string,
    cooking_levels: :string,
    description_2: :string,
    device_display: :string,
    function_list: [:string, array: true, default: []],
    gas_input: :string,
    installation: :string,
    lighting: :string,
    programmability: [:string, array: true, default: []],
    thermostat: :string,
    total_functions: [:string, array: true, default: []],


    # no
    hob: :string,
    safety_hob: :string,
    supplied_accessories_hob: [:string, array: true, default: []],
    main_oven_left: :string,
    capacity_main_oven: [:string, array: true, default: []],
    total_functions_main_oven: [:string, array: true, default: []],
    programmability_main_oven: [:string, array: true, default: []],
    cleaning_main_oven: :string,
    safety_main_oven: :string,
    supplied_accessories_main_oven: [:string, array: true, default: []],

    aux_oven_right: :string,
    capacity_aux_oven: [:string, array: true, default: []],
    cooking_levels_aux_oven: :string,
    thermostat_aux_oven: :string,
    cleaning_aux_oven: :string,
    lighting_aux_oven: :string,
    safety_aux_oven: :string,
    supplied_accessories_aux_oven: [:string, array: true, default: []],
    
    function_list_main_oven: [:string, array: true, default: []],
    function_list_aux_oven: [:string, array: true, default: []]
    # added

end

app/models/products/french_door_refrigeration.rb
class FrenchDoorRefrigeration < Product

  jsonb_accessor :data,
    accessories: [:string, array: true, default: []],
    defrost: :string,
    energy_consumption: :string,
    freezer_door: :string,
    gross_capacity: [:string, array: true, default: []],
    lighting: :string,
    nb_door_shelves: [:string, array: true, default: []],
    nb_drawers: [:string, array: true, default: []],
    nb_shelves: [:string, array: true, default: []],
    noise: :string,
    star_rating: :string,
    weight: :string,

    # no 
    shelves_main_compartment: [:string, array: true, default: []],
    drawers_main_compartment: [:string, array: true, default: []],
    door_shelves_main_compartment: [:string, array: true, default: []],
    lighting_main_compartment: :string,
    shelves_freezer: [:string, array: true, default: []],
    drawers_freezer: [:string, array: true, default: []],
    door_shelves_freezer: [:string, array: true, default: []],
    feature_list: [:string, array: true, default: []],
    performance: :string,   
    function_list: [:string, array: true, default: []]
end

app/models/products/fridge.rb
class Fridge < Product

  jsonb_accessor :data,
    accessories: [:string, array: true, default: []],
    defrost: :string,
    energy_consumption: :string,
    freezer_door: :string,
    gross_capacity: [:string, array: true, default: []],
    installation: :string,
    lighting: :string,
    door_shelves: [:string, array: true, default: []],
    drawers: [:string, array: true, default: []],
    shelves: [:string, array: true, default: []],
    star_rating: :string,


    function_list: [:string, array: true, default: []]

end

app/views/products/_file_attachment_fields.slim
.nested-fields.file-item
  - if f.object.attachment.present?
    .remove-attachment
      = link_to_remove_association f, class: 'btn btn-xs btn-danger pull-right' do
        .fa.fa-times

    .file-container
      = link_to "#{f.object.attachment.file.filename}", f.object.attachment.url, target: '_blank'

  - else
    = f.input :attachment, as: :file
    = f.input :attachment_cache, as: :hidden
    /= f.input :file_type, as: :string
    = f.input :file_type, as: :select, collection: SelectionControl.where(name: 'file type').map{ |ft| [ft.label, ft.value]}, label: "File Type"
    = f.input :description, as: :string

app/views/products/_image_attachment_fields.slim
.nested-fields.image-item
  - if f.object.present?
    .remove-attachment
      = link_to_remove_association f, class: 'btn btn-xs btn-danger pull-right' do
        .fa.fa-times
  .clearfix
  hr

  - if f.object.attachment.present?
    .image-container
      = image_tag f.object.attachment.url

  - else
    = f.input :attachment, as: :file
    = f.input :attachment_cache, as: :hidden

app/views/products/_list.slim
table.table class="table table-hover pointer"
    tr
      th Model #
      th Description
      th Aesthetic
      th Type
      
      //th style='width:300px;'

    - for product in @products
      tr onclick="location.href='#{product_path(product)}'"
        td= product.model_number
        td= product.description
        td= product.aesthetic
        
        td= I18n.t product.type, scope: [:options, :product_types]
        /td= number_to_currency(product.price)
        / td
        /   .btn-group.pull-right
        /     = link_to product_path(product), class: 'btn btn-default btn-xs' do
        /       i.fa.fa-eye
        /     = link_to edit_product_path(product), class: 'btn btn-default btn-xs' do
        /       i.fa.fa-pencil
        /     = link_to product_path(product), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
        /       i.fa.fa-trash-o

app/views/products/_modal_product_history.slim
#product-history-modal.modal.fade aria-labelledby="product-historyLabel" role="dialog" tabindex="-1" data={product_id: product.id, user_id: current_user.id}
  .modal-dialog.modal-lg role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#product-historyLabel.modal-title Product History
      .modal-body
        - if product.history.present?
          table.table
            thead
              tr
                th Date/Time
                th Username
                th Type
                th Comment
            tbody
              - product.history.each do |history_item|
                tr
                  td = history_item[:date]&.try(:to_s, :date_and_time)
                  td = history_item[:whodunnit]&.name
                  td = history_item[:item_type]
                  td = history_item[:text].html_safe

        - else
          p
            b No Product History available.

app/views/products/edit.html.slim
.container style='padding-bottom: 80px;'
  .row
    .col-xs-12
      h1 Edit Product

  .row
    .col-xs-12
      = simple_form_for @product, as: :product, url: product_path(@product) do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          => f.submit 'Update', class: 'btn btn-primary'
          =< link_to "Cancel", :back, class: 'btn btn-default'

app/views/products/index.html.slim
.container
  - if flash[:notice].present?
    div.alert.alert-danger role="alert"
      = notice
  .row
    .col-xs-6
      h1 Products
    .col-xs-2.col-xs-offset-4
      = link_to "+ Add Prodct", model_selection_new_product_path, class: 'btn btn-default btn-xs btn-model-selection'
  br
  / .row
  /  .col-xs-2
  /   = select_tag "by_type", options_for_select(Product.unique_type ), class: "form-control"
  .row
    = form_tag(products_path, method: :get) do
      .col-xs-2
        /= label_tag "type"
        = select_tag "by_type", options_for_select(Product.unique_type, params[:by_type]), prompt: "Select type",include_blank: true, class: "form-control", onchange: 'this.form.submit();'
      .col-xs-2
        /= label_tag "Aesthetic"
        = select_tag "by_aesthetic", options_for_select(Product.unique_aesthetic, params[:by_aesthetic] ), prompt: "Select aesthetic",include_blank: true, class: "form-control", onchange: 'this.form.submit();'
        /, onchange: 'this.form.submit();'
      .col-xs-4
        / = label_tag "General Search"
        = text_field_tag :search_products, nil, placeholder: "Try to type anything...", class: "form-control", value: params[:search_products]
        /= text_field_tag :by_type, nil, placeholder: "Search products ...", class: "form-control"
      / .col-xs-2
      /   = link_to "Export", products_path(format: "csv"), class: "export-btn"
      .col-xs-4
        /= label_tag ""
        => submit_tag "Search", class: "btn btn-info btn-xs search-btn",style: "" 
        =< link_to '<button type="button" class="btn btn-info btn-xs search-btn">Reset</button>'.html_safe, products_path

      / .col-xs-2   
      /   /= button_tag "Reset", class: "btn btn-info btn-xs search-btn", onchange: 'this.form.reset();'
      /   /= label_tag ""
      /   = link_to '<button type="button" class="btn btn-info btn-xs search-btn">Reset</button>'.html_safe, products_path
    
      

  br

  .row
    = render "products/list"

  / table.table class="table table-hover pointer"
  /   tr
  /     th Model #
  /     th Description
  /     th Aesthetic
  /     th Type
      
  /     //th style='width:300px;'

  /   - for product in @products
  /     tr onclick="location.href='#{product_path(product)}'"
  /       td= product.model_number
  /       td= product.description
  /       td= product.aesthetic
        
  /       td= I18n.t product.type, scope: [:options, :product_types]
  /       /td= number_to_currency(product.price)
  /       / td
  /       /   .btn-group.pull-right
  /       /     = link_to product_path(product), class: 'btn btn-default btn-xs' do
  /       /       i.fa.fa-eye
  /       /     = link_to edit_product_path(product), class: 'btn btn-default btn-xs' do
  /       /       i.fa.fa-pencil
  /       /     = link_to product_path(product), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
  /       /       i.fa.fa-trash-o
  .row
      = form_tag(products_export_path(format: "csv"), method: :get) do
        .col-xs-1
          = label_tag 'Export'
        .col-xs-2
          = select_tag "p_type", options_for_select(Product.unique_type), prompt: "Select type to Export",include_blank: true, class: "form-control", onchange: 'this.form.submit();'
        / .col-xs-2
        /   = text_field_tag :by_type, params[:by_type]
  = paginate @products
  


#modal-holder

app/views/products/show.html.slim
.container
  h3 #{@product.model_number}  #{@product.description}
  = I18n.t @product.type, scope: [:options, :product_types]

  .btn-group.pull-right
    = link_to edit_product_path(@product), class: 'btn btn-default btn-xs', title: 'Edit' do
      i.fa.fa-pencil
    = link_to copy_product_path(@product), class: 'btn btn-default btn-xs btn-copy', title: 'Copy' do
      i.fa.fa-copy
    = link_to product_path(@product), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs', title: 'Delete' do
      i.fa.fa-trash-o
    = link_to history_product_path(@product), class: 'btn btn-default btn-xs btn-history', title: 'Editing History' do
      i.fa.fa-folder

    a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" class='btn btn-default btn-xs' title='PDFs'
      i.fa.fa-file-o
      |&nbsp;PDFS&nbsp;
      span.caret
    ul.dropdown-menu
      li
        = link_to 'Specifications Sheet', product_path(@product, format: 'pdf', pdf: 'specifications'), target: '_blank'
      li
        = link_to 'Silent Salesman', product_path(@product, format: 'pdf', pdf: 'silent-salesmen'), target: '_blank'

  br
  br
  br

  = image_tag @product.cover_image.thumb

  br
  br

  h3 Basic Details
  table.table
    tr
      th Price
      td = number_to_currency(@product.price)
    tr
      th Description
      td = @product.description
    tr
      th Ean
      td = @product.ean
    tr
      th Finish
      td
        - if !dynamic_list(@product.finish).nil?
          ul
            - dynamic_list(@product.finish).each do |accessory|
              li
                =< "#{accessory}"
    tr
      th Aesthetic
      td = @product.aesthetic
    tr
      th Safety
      td
        - if !dynamic_list(@product.safety).nil?
          ul
            - dynamic_list(@product.safety).each do |accessory|
              li
                =< "#{accessory}"

    tr
      th Dimensions
      td = @product.dimensions
    tr
      th Power
      td = @product.power
    tr
      th Warranty
      td = @product.warranty
    tr
      th Status
      td = @product.status

    - if @product.try(:function_list).present?
      tr
        th Function List
        td
          ul style="column-count: 2;"
            - @product.function_list.reject { |x| x.empty? }.each do |function|
              li
                => image_tag(function_icon(function))
                /=< I18n.t("options.function_list.#{function}")
                =< function_des(function)

    tr
      th Supplied Accessories
      td
        - if !supplied_accessories(@product).nil?
          ul
            - supplied_accessories(@product).each do |accessory|
              li
                =< "#{accessory}"

    tr
      th Optional Accessories
      td
        - if !optional_accessories(@product).nil?
          ul
            - optional_accessories(@product).each do |accessory|
              li
                =< "#{accessory}"

    tr
      th Notes
      td = @product.notes

  #feature
    .feature-header
      h3 Features 
      button#featureBtn Show Feature List 
    .feature-content 
      table.table
        tr
          th Name
          th Description
        - @product.features.each do |feature|
          tr
            td = feature.name
            td = feature.try(:long_description)

  #details
    .details-header
      h3 Custom Details
      button#detailsBtn Show Detail List
    .details-content
      table.table
        = render "products/custom_detail/#{@product.type.underscore}", product: @product

  hr
  h3 Schematic Images
  .row
    - if @product.schematic_attachments.any?
      - @product.schematic_attachments.each do |image|
        .col-xs-3
          = image_tag image.attachment.thumb
    - else
      .col-xs-12
        p = "No Schematics Uploaded."

  hr
  h3 Product Images
  .row
    - if @product.image_attachments.any?
      - @product.image_attachments.each do |image|
        .col-xs-3
          = image_tag image.attachment.thumb
    - else
      .col-xs-12
        p = "No Images Uploaded."

  hr
  h3 Documents
  .row
    .col-xs-12
      - if @product.file_attachments.any?
        table class="table table-sm"
          tr 
            th File Name
            th File Type
            th Description
          - for file in @product.file_attachments
            tr 
              td = link_to "#{file.attachment.file.filename}", file.attachment.url, target: '_blank'
              td = file.file_type
              td = file.description
      - else
        p = "No Documents Uploaded."

  / hr
  / h3 Approvals
  / .row
  /   .col-xs-12
  /     - if @product.approvals.any?
  /       ul
  /         - @product.approvals.each do |file|
  /           li = link_to "#{file.approval_no}", file.approval_doc.url, target: '_blank'
  /     - else
  /       p = "No Approvals Uploaded."

  hr
  h3 Approvals
  .row
    .col-xs-12
      - if @product.approvals.any?
        table class="table table-sm"
          tr 
            th Approval NO.
            th Approval Type
            th Description
            th Effective Date
            th Expiry Date
            th Status
          - for appr in @product.approvals
            tr 
              td = link_to "#{appr.approval_no}", approval_path(appr)
              td.approval_type = appr.approval_type
              td = appr.description
              td = appr.effective_date
              td = appr.expiry_date
              td = appr.status 
      - else
        p = "No Approvals Uploaded."

br
br

#modal-container
#copy-modal-container

#feature-list-modal.modal.fade aria-labelledby="feature-listLabel" aria-hidden="true" role="dialog" tabindex="-1" data={}
  .modal-dialog.modal-dialog-centered role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#feature-listLabel.modal-title Feature List
      .modal-body
        ul
          - @product.features.each do |feature|
            li = feature.name


#detail-list-modal.modal.fade aria-labelledby="detail-listLabel" aria-hidden="true" role="dialog" tabindex="-1" data={}
  .modal-dialog.modal-dialog-centered role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#detail-listLabel.modal-title Detail List
      .modal-body
        ul.list-group
          - @custom_attributes.each do |attr|
            - if is_array(@product.data[attr])
              ul
                - dynamic_list(@product.data[attr]).each do |accessory|
                  li
                    =< "#{accessory}" 
            - if !is_array(@product.data[attr])
              ul
                li = @product.data[attr]
            hr